apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170295194
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170295194
    app.kubernetes.io/part-of: test-app-170295194
  name: java-quarkus-170295194
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170295194
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170295194
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170295194/java-quarkus-170295194@sha256:07875f76ec59c637fc47e564672e69ddce0a6d08853a7c261670fecd83f0682d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
